[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MATES"
authors = [{name = "Ruohan Wang", email = "ruohan_wang@brown.edu"}]
dynamic = ["version", "description"]
